name: build
run-name: build
on: [push]
jobs:
  build_linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            submodules: 'true'
      - name: Build
        run: |
            sudo apt-get update
            sudo apt-get upgrade -y
            sudo apt-get install -y libcairo2-dev libwebp-dev g++
            cmake -B build
            cmake --build build
      - uses: actions/upload-artifact@v4
        with:
            name: build_linux
            path: build
  build_mac:
    runs-on: macos-14
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            submodules: 'true'
      - name: Build
        run: |
            brew install pkg-config cairo webp
            cmake -B build
            cmake --build build
      - uses: actions/upload-artifact@v4
        with:
            name: build_mac
            path: build
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            submodules: 'true'
      - name: Build
        run: |
          ./libs/vcpkg/bootstrap-vcpkg.bat
          ./libs/vcpkg/vcpkg.exe install pkgconf:x64-windows-static cairo:x64-windows-static libwebp:x64-windows-static
          cmake -B build
          cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
            name: build_windows
            path: build
